// Barrel export for all hooks
export { useAuth } from './useAuth';
export {
  useStudentProfile,
  useUpdateProfile,
  useUploadCV,
  useRecommendedJobs,
  useSkillGaps,
  useStudentApplications,
  useStudentInsights,
  useJobs,
  useJob,
  useApplyToJob,
  useMatchResult,
} from './useStudent';
export {
  useCompanyDashboard,
  useCompanyJobs,
  useCreateJob,
  useUpdateJob,
  useDeleteJob,
  useCandidates,
  useCompanyApplications,
  useUpdateApplicationStatus,
  useCompanyAnalytics,
} from './useCompany';
export {
  useUniversityDashboard,
  useUniversityStructure,
  useUpdateStructure,
  useUniversityStudents,
  useUniversityAnalytics,
} from './useUniversity';
export {
  useDashboardMetrics,
  useSystemHealth,
  usePlatformMetrics,
  usePerformanceKPIs,
  useAdminUsers,
  useUpdateUserStatus,
  useCreateAdminUser,
  useUpdateAdminUser,
  useDeleteAdminUser,
  useInvalidateUserSessions,
  useAdminAccounts,
  useCreateAdminAccount,
  useUpdateAdminAccount,
  useDisableAdminAccount,
  useReactivateAdminAccount,
  useAdminRoles,
  useAdminPermissions,
  useCreateRole,
  useCreatePermission,
  useAssignRole,
  useActivityLog,
  useAuditLogs,
  useAiOperations,
  useAiMetrics,
  useAiModels,
  useEmailMonitoring,
  useTestSmtpConnection,
  useBackups,
  useCreateBackup,
  useVerifyBackup,
  useRestoreBackup,
  useSecurityAlerts,
  useSecurityStatus,
  usePlatformSettings,
  useUpdatePlatformSettings,
  useCompanies,
  useCrossPlatformAnalytics,
  useReviewUniversity,
  useAdminUniversities,
} from './useAdmin';
