import {
  ArrowsMerge,
  Brain,
  Briefcase,
  Buildings,
  Certificate,
  ChartBar,
  ChartLineDown,
  CheckCircle,
  ClipboardText,
  Compass,
  Database,
  FileArrowUp,
  FileMagnifyingGlass,
  FolderOpen,
  Gauge,
  GraduationCap,
  IdentificationCard,
  LightbulbFilament,
  LinkBreak,
  LinkSimple,
  ListMagnifyingGlass,
  MapTrifold,
  Network,
  Question,
  RoadHorizon,
  Scan,
  ShieldCheck,
  Student,
  SuitcaseSimple,
  Tag,
  TrendUp,
  UserCircleCheck,
  UsersThree,
  WarningCircle,
} from '@phosphor-icons/react';

export const landingIcons = {
  account: UserCircleCheck,
  ai: Brain,
  applications: ClipboardText,
  careerProfile: IdentificationCard,
  certificates: Certificate,
  company: Buildings,
  connected: Network,
  data: Database,
  education: GraduationCap,
  experience: Briefcase,
  extract: Scan,
  gap: LinkBreak,
  jobs: SuitcaseSimple,
  languages: Tag,
  market: TrendUp,
  match: LinkSimple,
  merge: ArrowsMerge,
  missingTrend: ChartLineDown,
  opportunity: ListMagnifyingGlass,
  projects: FolderOpen,
  readiness: Gauge,
  recommendations: Compass,
  question: Question,
  reports: ChartBar,
  resume: FileMagnifyingGlass,
  roadmap: RoadHorizon,
  security: ShieldCheck,
  skills: Tag,
  student: Student,
  success: CheckCircle,
  university: GraduationCap,
  upload: FileArrowUp,
  users: UsersThree,
  warning: WarningCircle,
  insight: LightbulbFilament,
  map: MapTrifold,
} as const;

export type LandingIconName = keyof typeof landingIcons;
